repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy ./api/app --ignore-missing-imports
        language: system
        always_run: true
        verbose: true
        pass_filenames: false
      - id: black
        name: black
        language: system
        entry: black --check . --diff
        types: [ python ]
        always_run: true
        pass_filenames: false