name: Having fun - API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./api/requirements.txt
      - name: Lint check the code
        run: |
          pip install black
          black --check api/
      - name: Strict typing check
        run: |
          pip install mypy
          mypy ./api/app/*.py
      - name: Bandit code security check
        run: |
          pip install bandit
          bandit ./api/app/*.py -ll
      - name: Dependencies security check
        run: |
          pip install safety
          safety check -r ./app/requirements.txt
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Deta Space Deployment Github Action
        uses: neobrains/space-deployment-github-action@v0.5
        with:
          access_token: ${{ secrets.DETA_SPACE_ACCESS_TOKEN }}
          project_id: ${{ secrets.DETA_SPACE_PROJECT_ID }}
          space_push: true
          list_on_discovery: true
